#!/usr/bin/env node
/**
 * STEP0-B codegen — JSON Schema -> TypeScript + Pydantic v2.
 *
 * Reads:  packages/schemas/schemas/contracts.schema.json
 * Emits:
 *   packages/schemas/generated/ts/contracts.ts
 *   packages/schemas/src/ovt_schemas/contracts.py
 *
 * Rules:
 *  - Pure Node, no external npm deps.
 *  - Deterministic (byte-identical across runs): no timestamps, no random.
 *  - LF line endings.
 *  - Emits $defs in schema order (already topological — leaf types first,
 *    so no forward refs needed). Assumes no $def/property name is an
 *    integer-like string (V8 hoists such keys), which holds for these contracts.
 */

import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const schema = JSON.parse(
  readFileSync(join(root, "schemas", "contracts.schema.json"), "utf8")
);

const defs = schema["$defs"] ?? {};

// ────────────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────────────

/** Return the $def name from a $ref string like "#/$defs/Foo" */
function refName(ref) {
  const m = ref.match(/^#\/\$defs\/(.+)$/);
  if (!m) throw new Error(`Unexpected $ref: ${ref}`);
  return m[1];
}

/** Is the schema property nullable (type array includes "null" or oneOf has null)? */
function isNullable(prop) {
  if (Array.isArray(prop.type) && prop.type.includes("null")) return true;
  if (prop.oneOf && prop.oneOf.some((s) => s.type === "null")) return true;
  return false;
}

// ────────────────────────────────────────────────────────────────────────────
// TypeScript codegen
// ────────────────────────────────────────────────────────────────────────────

function tsBareType(prop) {
  // $ref
  if (prop["$ref"]) return refName(prop["$ref"]);

  // oneOf with a $ref + null  (used for error_code)
  if (prop.oneOf) {
    const nonNull = prop.oneOf.filter((s) => s.type !== "null");
    if (nonNull.length === 1) return tsBareType(nonNull[0]);
    return nonNull.map(tsBareType).join(" | ");
  }

  const types = Array.isArray(prop.type) ? prop.type : [prop.type];
  const nonNullTypes = types.filter((t) => t !== "null");
  if (nonNullTypes.length > 1) {
    throw new Error(
      `Unsupported multi-type union (only [X, "null"] supported): ${JSON.stringify(prop.type)}`
    );
  }
  const t = nonNullTypes[0];

  // const → literal
  if (prop["const"] !== undefined) return JSON.stringify(prop["const"]);

  // enum → string literal union
  if (prop.enum) return prop.enum.map((v) => JSON.stringify(v)).join(" | ");

  // object with additionalProperties.$ref → Record<string, T>
  if (t === "object" && prop.additionalProperties && prop.additionalProperties["$ref"]) {
    return `Record<string, ${refName(prop.additionalProperties["$ref"])}>`;
  }
  // free-form object (["object","null"] or just "object")
  if (t === "object") return "Record<string, unknown>";

  // array
  if (t === "array") {
    if (prop.items) return `${tsBareType(prop.items)}[]`;
    return "unknown[]";
  }

  if (t === "string") return "string";
  if (t === "integer" || t === "number") return "number";
  if (t === "boolean") return "boolean";

  return "unknown";
}

function generateTs() {
  const lines = [];
  lines.push(
    "// AUTO-GENERATED by packages/schemas/scripts/codegen.mjs — DO NOT EDIT.",
    "// Source: packages/schemas/schemas/contracts.schema.json",
    ""
  );

  for (const [name, def] of Object.entries(defs)) {
    // Enum-like: plain string enum at top level
    if (def.type === "string" && def.enum) {
      const union = def.enum.map((v) => JSON.stringify(v)).join(" | ");
      if (def.description) lines.push(`/** ${def.description} */`);
      lines.push(`export type ${name} = ${union};`);
      lines.push("");
      continue;
    }

    // Registry map: object with additionalProperties.$ref (no own properties)
    if (
      def.type === "object" &&
      def.additionalProperties &&
      def.additionalProperties["$ref"] &&
      !def.properties
    ) {
      if (def.description) lines.push(`/** ${def.description} */`);
      lines.push(
        `export type ${name} = Record<string, ${refName(def.additionalProperties["$ref"])}>;`
      );
      lines.push("");
      continue;
    }

    // Regular object → interface
    if (def.type === "object" && def.properties) {
      if (def.description) lines.push(`/** ${def.description} */`);
      lines.push(`export interface ${name} {`);
      const required = new Set(def.required ?? []);
      for (const [field, prop] of Object.entries(def.properties)) {
        const isReq = required.has(field);
        const nullable = isNullable(prop);
        const baseType = tsBareType(prop);
        const fullType = nullable ? `${baseType} | null` : baseType;
        // Optional (?) if not in required OR if the field is nullable (has | null)
        const optMark = !isReq || nullable ? "?" : "";
        lines.push(`  ${field}${optMark}: ${fullType};`);
      }
      lines.push("}");
      lines.push("");
      continue;
    }

    // Fallback
    lines.push(`export type ${name} = unknown;`);
    lines.push("");
  }

  return lines.join("\n");
}

// ────────────────────────────────────────────────────────────────────────────
// Python (Pydantic v2) codegen
// ────────────────────────────────────────────────────────────────────────────

const LINE_LENGTH = 100;

function pyBareType(prop) {
  // $ref
  if (prop["$ref"]) return refName(prop["$ref"]);

  // oneOf with $ref + null
  if (prop.oneOf) {
    const nonNull = prop.oneOf.filter((s) => s.type !== "null");
    if (nonNull.length === 1) return pyBareType(nonNull[0]);
    return nonNull.map(pyBareType).join(" | ");
  }

  const types = Array.isArray(prop.type) ? prop.type : [prop.type];
  const nonNullTypes = types.filter((t) => t !== "null");
  if (nonNullTypes.length > 1) {
    throw new Error(
      `Unsupported multi-type union (only [X, "null"] supported): ${JSON.stringify(prop.type)}`
    );
  }
  const t = nonNullTypes[0];

  // const → Literal
  if (prop["const"] !== undefined) return `Literal[${JSON.stringify(prop["const"])}]`;

  // enum → Literal[...]
  if (prop.enum) {
    return `Literal[${prop.enum.map((v) => JSON.stringify(v)).join(", ")}]`;
  }

  // object with additionalProperties.$ref → dict[str, T]
  if (t === "object" && prop.additionalProperties && prop.additionalProperties["$ref"]) {
    return `dict[str, ${refName(prop.additionalProperties["$ref"])}]`;
  }
  // free-form object (["object","null"] or plain "object")
  if (t === "object") return "dict[str, Any]";

  // array
  if (t === "array") {
    if (prop.items) return `list[${pyBareType(prop.items)}]`;
    return "list[Any]";
  }

  if (t === "string") return "str";
  if (t === "integer") return "int";
  if (t === "number") return "float";
  if (t === "boolean") return "bool";

  return "Any";
}

/**
 * Build the full annotation for a property.
 * Returns { annotation: string, defaultStr: string|null }
 *
 * Nullable logic:
 *  - If type includes null → add "| None" to annotation
 *  - If not required AND not nullable → annotation stays as-is, default is None
 *    (but only add "| None" to annotation if there's no explicit non-None default)
 *  - If not required AND nullable → "X | None"
 */
function pyField(prop, isRequired) {
  const nullable = isNullable(prop);
  const hasSchemaDefault = "default" in prop;
  const schemaDefault = prop.default;

  const bare = pyBareType(prop);

  // Determine if we add "| None" to the type
  // We add it when the field is nullable (type includes null) OR when the
  // field is optional and has no schema default (field is entirely absent = None)
  // BUT: if the field is optional with an explicit non-None default (e.g. default:[]),
  //      we do NOT add | None.
  let annotation;
  let defaultStr;

  if (isRequired && !nullable && !hasSchemaDefault) {
    // Strictly required, non-nullable, no default
    annotation = bare;
    defaultStr = null;
  } else if (nullable) {
    // Nullable — always add | None
    annotation = `${bare} | None`;
    if (hasSchemaDefault) {
      defaultStr = pyDefaultValue(schemaDefault);
    } else {
      defaultStr = "None";
    }
  } else if (hasSchemaDefault) {
    // Not nullable, but has a schema default
    // Don't add | None — use the literal default
    annotation = bare;
    defaultStr = pyDefaultValue(schemaDefault);
  } else {
    // Not required, no schema default, not nullable
    annotation = `${bare} | None`;
    defaultStr = "None";
  }

  return { annotation, defaultStr };
}

function pyDefaultValue(d) {
  if (d === null) return "None";
  if (typeof d === "boolean") return d ? "True" : "False";
  if (typeof d === "string") return JSON.stringify(d);
  if (typeof d === "number") return String(d);
  if (Array.isArray(d) && d.length === 0) return "[]";
  // Fail loud rather than silently emit None for an unhandled default shape.
  throw new Error(`Unsupported schema default (extend pyDefaultValue): ${JSON.stringify(d)}`);
}

/**
 * Wrap a "name: Annotation = default" line to respect LINE_LENGTH.
 * Returns array of line strings (without trailing newline).
 * Only wraps Literal[...] annotations.
 */
function wrapFieldLine(indent, name, annotation, defaultStr) {
  const suffix = defaultStr !== null ? ` = ${defaultStr}` : "";
  const singleLine = `${indent}${name}: ${annotation}${suffix}`;
  if (singleLine.length <= LINE_LENGTH) return [singleLine];

  // Only wrap Literal[...] annotations
  const litMatch = annotation.match(/^(Literal\[)(.+?)(\])$/s);
  if (!litMatch) {
    // Can't wrap — return as-is (will be flagged by ruff E501 only if > 100)
    return [singleLine];
  }

  // Parse items from the inner string (comma-separated JSON strings)
  const innerStr = litMatch[2];
  const items = [];
  let cur = "";
  let inStr = false;
  let escape = false;
  for (const ch of innerStr) {
    if (escape) { cur += ch; escape = false; continue; }
    if (ch === "\\") { cur += ch; escape = true; continue; }
    if (ch === '"') { inStr = !inStr; cur += ch; continue; }
    if (!inStr && ch === ",") { items.push(cur.trim()); cur = ""; continue; }
    cur += ch;
  }
  if (cur.trim()) items.push(cur.trim());

  const prefixFirst = `${indent}${name}: Literal[`;
  const prefixRest = " ".repeat(prefixFirst.length);

  const resultLines = [];
  let current = prefixFirst;
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const isLast = i === items.length - 1;
    const addition = isLast ? item : item + ", ";
    if (current !== prefixFirst && current.length + addition.length > LINE_LENGTH) {
      resultLines.push(current.trimEnd());
      current = prefixRest + addition;
    } else {
      current += addition;
    }
  }
  resultLines.push(current + "]" + suffix);
  return resultLines;
}

/**
 * Wrap a top-level "Name = Literal[...]" assignment.
 */
function wrapTopLevelLiteral(name, enumValues) {
  const items = enumValues.map((v) => JSON.stringify(v));
  const prefixFirst = `${name} = Literal[`;
  const prefixRest = " ".repeat(prefixFirst.length);
  const singleLine = `${prefixFirst}${items.join(", ")}]`;
  if (singleLine.length <= LINE_LENGTH) return [singleLine];

  const resultLines = [];
  let current = prefixFirst;
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const isLast = i === items.length - 1;
    const addition = isLast ? item : item + ", ";
    // The LAST item is followed by the closing ']' on the same line — count that bracket in the
    // break decision so the final line can't overflow LINE_LENGTH by one (e.g. a 101-char ErrorCode
    // Literal). Without this, a literal whose last item lands exactly at the limit emits a 101-col
    // line that ruff E501 rejects.
    const additionLen = addition.length + (isLast ? 1 : 0);
    if (current !== prefixFirst && current.length + additionLen > LINE_LENGTH) {
      resultLines.push(current.trimEnd());
      current = prefixRest + addition;
    } else {
      current += addition;
    }
  }
  resultLines.push(current + "]");
  return resultLines;
}

/** Truncate a docstring to fit within LINE_LENGTH (accounting for 4-space indent + `"""`). */
function truncateDocstring(text, indent = "    ") {
  // Total allowed: LINE_LENGTH - indent.length - 6 (for opening+closing """)
  const maxLen = LINE_LENGTH - indent.length - 6; // 6 = len('"""' + '"""')
  if (text.length <= maxLen) return text;
  // Truncate at the last word boundary before the limit (avoid mid-word cuts),
  // then strip trailing punctuation/space before the ellipsis.
  let cut = text.slice(0, maxLen - 1);
  const lastSpace = cut.lastIndexOf(" ");
  if (lastSpace > maxLen * 0.6) cut = cut.slice(0, lastSpace);
  return cut.replace(/[\s.,;:]+$/, "") + "…";
}

function generatePy() {
  const allNames = Object.keys(defs);

  const lines = [];
  lines.push(
    "# AUTO-GENERATED by packages/schemas/scripts/codegen.mjs — DO NOT EDIT.",
    "# Source: packages/schemas/schemas/contracts.schema.json",
    "from __future__ import annotations",
    "",
    "from typing import Any, Literal",
    "",
    "from pydantic import BaseModel, ConfigDict",
    ""
  );

  // __all__
  {
    const allQuoted = allNames.map((n) => `"${n}"`).join(", ");
    const singleLine = `__all__ = [${allQuoted}]`;
    if (singleLine.length <= LINE_LENGTH) {
      lines.push(singleLine);
    } else {
      lines.push("__all__ = [");
      for (const n of allNames) lines.push(`    "${n}",`);
      lines.push("]");
    }
  }

  for (const [name, def] of Object.entries(defs)) {
    lines.push("", ""); // two blank lines before each top-level def (PEP8 E302/E305)

    // String enum → top-level type alias
    if (def.type === "string" && def.enum) {
      lines.push(...wrapTopLevelLiteral(name, def.enum));
      continue;
    }

    // Registry map (object with additionalProperties.$ref, no properties)
    if (
      def.type === "object" &&
      def.additionalProperties &&
      def.additionalProperties["$ref"] &&
      !def.properties
    ) {
      const inner = refName(def.additionalProperties["$ref"]);
      lines.push(`${name} = dict[str, ${inner}]`);
      continue;
    }

    // Object with properties → Pydantic BaseModel
    if (def.type === "object" && def.properties) {
      lines.push(`class ${name}(BaseModel):`);
      if (def.description) {
        const doc = truncateDocstring(def.description, "    ");
        lines.push(`    """${doc}"""`);
      }
      // Enforce the JSON Schema contract: reject unknown keys (additionalProperties:false)
      // AND reject type coercion (e.g. "123" for an integer field), matching the schema's
      // declared types / integer-ms contract instead of silently coercing.
      lines.push('    model_config = ConfigDict(extra="forbid", strict=True)');

      const required = new Set(def.required ?? []);
      const props = Object.entries(def.properties);

      if (props.length === 0) {
        lines.push("    pass");
        continue;
      }

      // Split: fields without defaults must come before fields with defaults.
      const reqNoDefault = [];
      const withDefault = [];

      for (const [field, prop] of props) {
        const isReq = required.has(field);
        const { annotation, defaultStr } = pyField(prop, isReq);
        if (defaultStr === null) {
          reqNoDefault.push([field, annotation, null]);
        } else {
          withDefault.push([field, annotation, defaultStr]);
        }
      }

      for (const [field, annotation, defVal] of reqNoDefault) {
        lines.push(...wrapFieldLine("    ", field, annotation, null));
      }
      for (const [field, annotation, defVal] of withDefault) {
        lines.push(...wrapFieldLine("    ", field, annotation, defVal));
      }

      continue;
    }

    // Fallback
    lines.push(`${name} = Any`);
  }

  // Ensure file ends with a single newline
  lines.push("");
  return lines.join("\n");
}

// ────────────────────────────────────────────────────────────────────────────
// Write outputs (LF line endings, byte-deterministic)
// ────────────────────────────────────────────────────────────────────────────

function lf(s) {
  return s.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

const tsOut = lf(generateTs());
const pyOut = lf(generatePy());

mkdirSync(join(root, "generated", "ts"), { recursive: true });
mkdirSync(join(root, "src", "ovt_schemas"), { recursive: true });

writeFileSync(join(root, "generated", "ts", "contracts.ts"), tsOut);
writeFileSync(join(root, "src", "ovt_schemas", "contracts.py"), pyOut);

console.log("codegen: wrote generated/ts/contracts.ts");
console.log("codegen: wrote src/ovt_schemas/contracts.py");
