#!/usr/bin/env node
/**
 * Minimal codegen script — STEP0-A skeleton.
 *
 * Reads packages/schemas/schemas/_placeholder.schema.json and emits:
 *   packages/schemas/generated/ts/_placeholder.ts
 *   packages/schemas/generated/py/_placeholder.py
 *
 * In STEP0-B this will be replaced by a real JSON Schema → Pydantic + TS generator
 * (e.g. json-schema-to-typescript + datamodel-code-generator).
 */

import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const schema = JSON.parse(
  readFileSync(join(root, "schemas", "_placeholder.schema.json"), "utf8")
);

const title = schema.title ?? "_Placeholder";
const safeName = title.replace(/[^A-Za-z0-9_]/g, "_");

// ── TypeScript output ──────────────────────────────────────────────────────
const tsOut = `\
// AUTO-GENERATED by packages/schemas/scripts/codegen.mjs — DO NOT EDIT.
// Source: schemas/_placeholder.schema.json

/** ${schema.description ?? ""} */
export interface ${safeName} {
  ok: boolean;
}
`;

// ── Python output ──────────────────────────────────────────────────────────
// STEP0-A placeholder is intentionally stdlib-only (dataclass, not pydantic):
// the scaffold declares no third-party deps, so a pydantic BaseModel would be
// un-importable in a fresh `uv sync`. The real JSON Schema → Pydantic generator
// (and the pydantic dependency) arrives in STEP0-B.
// Truncate description to fit ruff line-length (100 chars for the docstring line)
const maxDocLen = 80;
const rawDesc = schema.description ?? "";
const docDesc = rawDesc.length > maxDocLen ? rawDesc.slice(0, maxDocLen - 1) + "…" : rawDesc;

const pyOut = `\
# AUTO-GENERATED by packages/schemas/scripts/codegen.mjs — DO NOT EDIT.
# Source: schemas/_placeholder.schema.json
from __future__ import annotations

from dataclasses import dataclass


@dataclass
class ${safeName}:
    """${docDesc}"""

    ok: bool
`;

mkdirSync(join(root, "generated", "ts"), { recursive: true });
mkdirSync(join(root, "generated", "py"), { recursive: true });

writeFileSync(join(root, "generated", "ts", "_placeholder.ts"), tsOut);
writeFileSync(join(root, "generated", "py", "_placeholder.py"), pyOut);

console.log("codegen: wrote generated/ts/_placeholder.ts");
console.log("codegen: wrote generated/py/_placeholder.py");
