# AUTO-GENERATED by packages/schemas/scripts/codegen.mjs — DO NOT EDIT.
# Source: packages/schemas/schemas/contracts.schema.json
from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict

__all__ = [
    "Word",
    "TranscriptLine",
    "Transcript",
    "DubbingSegment",
    "TranslationResult",
    "Cue",
    "ErrorCode",
    "UploadSession",
    "AigcMarking",
    "JobPlan",
    "JobArtifacts",
    "Job",
    "ModelRef",
    "WorkerMeta",
    "Manifest",
    "LanguageCapability",
    "LanguageCapabilities",
]


class Word(BaseModel):
    """A single recognized word with millisecond timing."""
    model_config = ConfigDict(extra="forbid", strict=True)
    text: str
    start_ms: int
    end_ms: int


class TranscriptLine(BaseModel):
    """One line of source transcript with word-level timing."""
    model_config = ConfigDict(extra="forbid", strict=True)
    index: int
    start_ms: int
    end_ms: int
    source_text: str
    words: list[Word]
    speaker_id: str = "SPEAKER_00"


class Transcript(BaseModel):
    """ASR output: ordered transcript lines for the source media."""
    model_config = ConfigDict(extra="forbid", strict=True)
    source_language: str
    lines: list[TranscriptLine]
    asr_provider: str


class DubbingSegment(BaseModel):
    """A translated/timed segment for TTS + alignment."""
    model_config = ConfigDict(extra="forbid", strict=True)
    segment_id: str
    index: int
    speaker_id: str
    start_ms: int
    end_ms: int
    target_duration_ms: int
    source_text: str
    target_text: str
    voice_id: str | None = None
    tts_provider: str | None = None
    keep_original: bool = False
    align_method: str | None = None
    align_ratio: float | None = None
    needs_review: bool = False


class TranslationResult(BaseModel):
    """MT output: translated dubbing segments."""
    model_config = ConfigDict(extra="forbid", strict=True)
    source_language: str
    target_language: str
    mt_provider: str
    segments: list[DubbingSegment]


class Cue(BaseModel):
    """A subtitle cue. source_text is present only when subtitle_lang=bilingual."""
    model_config = ConfigDict(extra="forbid", strict=True)
    index: int
    start_ms: int
    end_ms: int
    target_text: str
    source_text: str | None = None


ErrorCode = Literal["over_duration", "unsupported_format", "upload_too_large",
                    "source_verify_failed", "source_fetch_failed", "unsupported_language_pair",
                    "no_tts_model_for_language", "free_pool_exhausted", "worker_lost",
                    "processing_timeout", "daily_cap_reached", "internal_error",
                    "deadline_exceeded"]


class UploadSession(BaseModel):
    """A direct-to-R2 upload session (D1 upload_sessions). 1h TTL."""
    model_config = ConfigDict(extra="forbid", strict=True)
    upload_session_id: str
    anon_or_user_id: str
    source_key: str
    declared_bytes: int
    declared_type: str
    status: Literal["pending", "verified", "consumed", "expired"]
    created_at: int
    expires_at: int


class AigcMarking(BaseModel):
    """AIGC legal-marking state for a Job (capability path always present; §14 only toggles)."""
    model_config = ConfigDict(extra="forbid", strict=True)
    enabled: bool
    implicit: bool
    explicit: bool
    form: Literal["tail_notice", "corner_label", "disclosure_only"]
    applied: bool | None = None


class JobPlan(BaseModel):
    """Chosen provider plan. tts is null for subtitle_only jobs."""
    model_config = ConfigDict(extra="forbid", strict=True)
    asr: str
    mt: str
    tts: str | None = None


class JobArtifacts(BaseModel):
    """R2 object keys for produced artifacts (set as the Job completes)."""
    model_config = ConfigDict(extra="forbid", strict=True)
    video_key: str | None = None
    srt_key: str | None = None


class Job(BaseModel):
    """Authoritative job record (control-plane D1 row / schemas source of truth). 4-state…"""
    model_config = ConfigDict(extra="forbid", strict=True)
    job_id: str
    anon_or_user_id: str
    tier: Literal["tier1"]
    status: Literal["queued", "running", "done", "failed"]
    source_type: Literal["upload"]
    upload_session_id: str
    target_lang: str
    output_mode: Literal["subtitle_only", "dub_only", "both"]
    subtitle_delivery: Literal["srt", "burned", "both"]
    subtitle_lang: Literal["target", "bilingual"]
    plan: JobPlan
    settings_version: int
    aigc_marking: AigcMarking
    priority: int
    enqueue_at: int
    deadline_at: int
    created_at: int
    expires_at: int
    artifacts: JobArtifacts
    attempt: int
    claim_version: int
    counted_job: bool
    counted_minutes: bool
    refunded: bool
    current_stage: str | None = None
    declared_bytes: int | None = None
    verified_bytes: int | None = None
    source_lang_hint: str | None = None
    detected_source_lang: str | None = None
    source_lang_confidence: float | None = None
    advisory_duration_ms: int | None = None
    started_at: int | None = None
    lease_expires_at: int | None = None
    finished_at: int | None = None
    data_purged_at: int | None = None
    error_code: ErrorCode | None = None
    error_detail: str | None = None


class ModelRef(BaseModel):
    """A model/binary reference with version + sha256 (supply-chain pin)."""
    model_config = ConfigDict(extra="forbid", strict=True)
    name: str
    version: str | None = None
    sha256: str | None = None


class WorkerMeta(BaseModel):
    """Worker-side metadata recorded in manifest.json."""
    model_config = ConfigDict(extra="forbid", strict=True)
    ffprobe: dict[str, Any] | None = None
    aigc_embed_method: str | None = None
    models: list[ModelRef] = []


class Manifest(BaseModel):
    """manifest.json: a Job projection plus worker_meta, written into the job directory by the…"""
    model_config = ConfigDict(extra="forbid", strict=True)
    job: Job
    worker_meta: WorkerMeta


class LanguageCapability(BaseModel):
    """Capabilities for one target locale (keyed by BCP-47 in the registry)."""
    model_config = ConfigDict(extra="forbid", strict=True)
    mt_supported: bool
    subtitle_supported: bool
    tts_supported: bool
    tts_models: list[str]
    burn_font: str
    license_status: str
    quality_tier: str
    default_voice: str | None = None


LanguageCapabilities = dict[str, LanguageCapability]
